     
package Controlador;

import Controlador._principal;
import Vista.jFrameProductos;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;




/**
 *
 * @author Hp
 */
public class Inicio_sesion extends javax.swing.JFrame {

    /**
     * Creates new form Inicio_seccion
     */
    public Inicio_sesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        button2 = new java.awt.Button();
        button3 = new java.awt.Button();
        button1 = new java.awt.Button();
        jLabel6 = new javax.swing.JLabel();
        jLabelCont = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jButtonEntrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButtonEntrar1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        _Contraseña = new javax.swing.JPasswordField();
        checkbox1 = new java.awt.Checkbox();
        jButtonEntrar2 = new javax.swing.JButton();
        jButtonEntrar3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();

        button2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        button2.setLabel("Cancelar");

        button3.setLabel("button3");

        button1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        button1.setLabel("Entrar");
        button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button1MouseClicked(evt);
            }
        });
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        jLabelCont.setBackground(new java.awt.Color(20, 137, 234));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Entrar");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(102, 204, 255)));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCheckBox1.setText("jCheckBox1");

        jButton2.setText("Cancelar");

        jButtonEntrar.setBackground(new java.awt.Color(51, 102, 255));
        jButtonEntrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonEntrar.setForeground(new java.awt.Color(153, 255, 255));
        jButtonEntrar.setText("Cancelar");
        jButtonEntrar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        jButtonEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEntrarMouseClicked(evt);
            }
        });

        jButtonEntrar1.setBackground(new java.awt.Color(51, 102, 255));
        jButtonEntrar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonEntrar1.setForeground(new java.awt.Color(153, 255, 255));
        jButtonEntrar1.setText("Entrar");
        jButtonEntrar1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        jButtonEntrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEntrar1MouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(125, 185, 246));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 255)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setText("Usuario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, 17));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 255));
        jLabel3.setText("Contraseña");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 20));

        jLabelUsuario.setBackground(new java.awt.Color(20, 137, 255));
        jLabelUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(0, 0, 153));
        jLabelUsuario.setText("'Eliza perez'");
        jLabelUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 255, 255), new java.awt.Color(153, 153, 0)));
        jLabelUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLabelUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 280, 31));

        jPanel4.setBackground(new java.awt.Color(9, 125, 218));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 153, 255)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 255));
        jLabel14.setText("¡Bienvenido!");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel15.setForeground(new java.awt.Color(0, 51, 255));
        jLabel15.setText("Distribuidora\"Rivas suarez\"");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/saludo (1).png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 65, 67));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 90));

        _Contraseña.setBackground(new java.awt.Color(20, 137, 255));
        _Contraseña.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        _Contraseña.setForeground(new java.awt.Color(0, 0, 153));
        _Contraseña.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 255, 255), new java.awt.Color(153, 153, 0)));
        _Contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _ContraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(_Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 280, 30));

        checkbox1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        checkbox1.setForeground(new java.awt.Color(51, 102, 255));
        checkbox1.setLabel("Mostrar contraseña");
        checkbox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkbox1MouseClicked(evt);
            }
        });
        jPanel1.add(checkbox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, 20));

        jButtonEntrar2.setBackground(new java.awt.Color(0, 102, 204));
        jButtonEntrar2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonEntrar2.setForeground(new java.awt.Color(153, 255, 255));
        jButtonEntrar2.setText("Cancelar");
        jButtonEntrar2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        jButtonEntrar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEntrar2MouseClicked(evt);
            }
        });
        jPanel1.add(jButtonEntrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 90, 30));

        jButtonEntrar3.setBackground(new java.awt.Color(0, 102, 204));
        jButtonEntrar3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonEntrar3.setForeground(new java.awt.Color(153, 255, 255));
        jButtonEntrar3.setText("Entrar");
        jButtonEntrar3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        jButtonEntrar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEntrar3MouseClicked(evt);
            }
        });
        jButtonEntrar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrar3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEntrar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 90, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 360, 470));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo de michelada naranja ilustrado  (4).png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 1370, 760));
        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseClicked
        
    }//GEN-LAST:event_button1MouseClicked

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed

    private void jLabelUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLabelUsuarioActionPerformed

    }//GEN-LAST:event_jLabelUsuarioActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEntrarMouseClicked
          
      

    }//GEN-LAST:event_jButtonEntrarMouseClicked

    private void _ContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__ContraseñaActionPerformed
      
    }//GEN-LAST:event__ContraseñaActionPerformed

    private void checkbox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkbox1MouseClicked
         boolean a = false;
   
       if (a){
           _Contraseña.setEchoChar((char)0);
            a = false;
}else{
            char i = 0;
         _Contraseña.setEchoChar(i);
          a = true;
       }
    }//GEN-LAST:event_checkbox1MouseClicked

    private void jButtonEntrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEntrar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEntrar1MouseClicked

    private void jButtonEntrar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEntrar3MouseClicked
        // String Usuario="'Eliza perez'";
       // String Contraseña="Eliza43";
        
        

       // String Cont=new String(_Contraseña.getPassword());
       // if(jLabelUsuario.getText().equals(Usuario)&& Cont.equals(Contraseña)){

         //   _principal RT = null;
         //    try {
            //     RT = new _principal();
            // } catch (SQLException ex) {
            //     Logger.getLogger(Inicio_sesion.class.getName()).log(Level.SEVERE, null, ex);
           //  }
           // RT.setVisible(true);
           // dispose();

           // JOptionPane.showMessageDialog(null,jLabelUsuario.
           //     getText(),"BIENVENIDA",JOptionPane.INFORMATION_MESSAGE);
       // }else{
        //    JOptionPane.showMessageDialog( this,"Error de contraseña");

       // }
    }//GEN-LAST:event_jButtonEntrar3MouseClicked

    private void jButtonEntrar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEntrar2MouseClicked
     
    
JDialog.setDefaultLookAndFeelDecorated(true); 
int resp = JOptionPane.showConfirmDialog(null,
"¿ Esta seguro que quiere cancelar ?",  

"Advetencia",

 JOptionPane. YES_NO_OPTION,

 JOptionPane.QUESTION_MESSAGE);

 setVisible(false);
 
if (resp != JOptionPane.NO_OPTION) {
        } else {
    setVisible(true);
        }

    }//GEN-LAST:event_jButtonEntrar2MouseClicked

    private void jButtonEntrar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrar3ActionPerformed

try{
          dispose();
            _principal na=new _principal();
            na.setVisible(true);
        }catch (SQLException ex){
            java.util.logging.Logger.getLogger(_principal.class.getName()).
            log(java.util.logging.Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_jButtonEntrar3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio_sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio_sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio_sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio_sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio_sesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField _Contraseña;
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.Checkbox checkbox1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JButton jButtonEntrar1;
    private javax.swing.JButton jButtonEntrar2;
    private javax.swing.JButton jButtonEntrar3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jLabelCont;
    private javax.swing.JTextField jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
